from . import start
from . import backs
from . import admin_stickers
from . import admin_update_stickers
from . import admin_menu
from . import admin_orders
from . import user_menu
from . import user_orders
from . import user_profile
